---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - maintenance.mamrezb.com
  resources:
  - servicecheckers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.mamrezb.com
  resources:
  - servicecheckers/finalizers
  verbs:
  - update
- apiGroups:
  - maintenance.mamrezb.com
  resources:
  - servicecheckers/status
  verbs:
  - get
  - patch
  - update
