# This rule is not used by the project maintenance-window-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over maintenance.mamrezb.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: maintenance-window-manager
    app.kubernetes.io/managed-by: kustomize
  name: servicechecker-admin-role
rules:
- apiGroups:
  - maintenance.mamrezb.com
  resources:
  - servicecheckers
  verbs:
  - '*'
- apiGroups:
  - maintenance.mamrezb.com
  resources:
  - servicecheckers/status
  verbs:
  - get
