apiVersion: maintenance.mamrezb.com/v1alpha1
kind: ServiceChecker
metadata:
  labels:
    app.kubernetes.io/name: maintenance-window-manager
    app.kubernetes.io/managed-by: kustomize
  name: servicechecker-sample
spec:
  services:
    - name: kubernetes
      namespace: default
      critical: true
    - name: dummy-service
      namespace: default
      critical: false