name: Draft Release Notes

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create draft release for (without v prefix, e.g. 0.1.0)'
        required: true

jobs:
  draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          name: v${{ github.event.inputs.version }}
          tag: v${{ github.event.inputs.version }}
          version: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 