{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["maintenance.mamrezb.com"]
    resources: ["servicecheckers", "servicecheckers/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: {{ if .Values.serviceAccount.name }}
      {{ .Values.serviceAccount.name }}
    {{ else }}
      {{ .Values.nameOverride | default "maintenance-window-manager" }}
    {{ end }}
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
