apiVersion: v1
kind: Service
metadata:
  name: {{ include "maintenance-window-manager.fullname" . }}-api
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.nameOverride | default "maintenance-window-manager" }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: api
      port: {{ .Values.apiPort }}
      targetPort: api
      protocol: TCP
